server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/**.xml
  type-aliases-package: com.lopo.domain

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nc_order
    username: root 
    password: 123456
  application:
    name: orderService

  cloud:
    nacos:
      server-addr: http://127.0.0.1:8848
    loadbalancer:
      nacos:
        enabled: true
